#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Feb 12 12:29:10 2023

@author: legend
"""


#------------------------TESTING OUR CLASSIFEIRS-----------------------------------

#---1--LEAVE ONE OUT------------


#---Typically used when we have a small number of examples----So we want as much training data as posssible as we build our model

#--Removes 1 from our examples, trainon  N-1, test on the one, put one back and remove another , train on n-1....repeat, average results

def leaveOneOut(examples, method, toPrint = True):
    truePos, falsePos, trueNeg, falseNeg = 0, 0, 0, 0
    for i in range(len(examples)):
        testCase = examples[i]
        trainingData = examples[0:i] + examples[i+1:]
        results = method(trainingData, [testCase])
        truePos += results[0]
        falsePos += results[1]
        trueNeg += results[2]
        falseNeg += results[3]
    if toPrint:
        getStats(truePos, falsePos, trueNeg, falseNeg)
    return truePos, falsePos, trueNeg, falseNeg




#---REPEATED RANDOM SUB SMAPLING 

Whe you have 