#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Feb 18 13:08:32 2023

@author: legend
"""


#------------------RECIEVER OPERATING CHARACTERISTIC------------------------------------------------
def buildROC(trainingSet, testSet, title, plot = True):
    model = buildModel(trainingSet, True)
    xVals, yVals = [], []
    p = 0.0
    while p <= 1.0:
        truePos, falsePos, trueNeg, falseNeg =\
                               applyModel(model, testSet,
                               'Survived', p)
        xVals.append(1.0 - specificity(trueNeg, falsePos))
        yVals.append(sensitivity(truePos, falseNeg))
        p += 0.01
    auroc = sklearn.metrics.auc(xVals, yVals, True)
    if plot:
        pylab.plot(xVals, yVals)
        pylab.plot([0,1], [0,1])
        title = title + '\nAUROC = ' + str(round(auroc,3))
        pylab.title(title)
        pylab.xlabel('1 - specificity')
        pylab.ylabel('Sensitivity')
    return auroc
#not wanting to make a decision about the WHERE the cut off anf insteadt look at all possible cut offs and look at the shape of it----------------------------------
#we take taining andd test set, biuild one model, and vary p and call p;llly model with the saame model and test set for diff Ps and keep track of thos results nd plot  Sensu=itvyt on Y and x will have 1- specificity
